random method switched to sample
CaiqueMitsuoka/randsome_meetup pull request #11
Opened 2017-02-12 14:35 UTC by Vitormdias

Solves issue #8

2017-02-12 15:08 UTC, vitortalaia requested changes

2017-02-12 15:08 UTC, vitortalaia commented on app/controllers/events_controller.rb
> +    person = attendes.sample.member
What about removing this logic from the controller? Something like creating a `random_atendee` method on the service.

I also think we're gonna need to make a request to `/members/:member_id` to get a standardized profile image, as shown [here](https://www.meetup.com/pt-BR/meetup_api/docs/2/member/?uri=%2Fmeetup_api%2Fdocs%2F2%2Fmember%2F#get).

2017-02-12 17:07 UTC, Vitormdias commented on app/controllers/events_controller.rb
> +    person = attendes.sample.member
@vitortalaia do you think we still need the ```attendance``` method on the service? we could just call a ```random attendee``` method from the controller

2017-02-12 17:35 UTC, vitortalaia commented on app/controllers/events_controller.rb
> +    person = attendes.sample.member
@Vitormdias I agree, we can just call `randon_attendee` from the controller. But I think it's better to keep the `attendance` method on the service, as we can call it from within the `randon_attendee` to get the participants.

2017-02-12 22:00 UTC, Vitormdias commented on app/controllers/events_controller.rb
> +    person = attendes.sample.member
Controller:
```ruby
def random
    person = meetup.random_attendee(urlname , event_id)
    @image = meetup.profile_image(person[:id])
    @name = person[:name]
end
```
Service:
```ruby
def profile_image (member_id)
    user = parse_json ( get("/members/#{member_id}") )
    user[:photo].photo_link
end

def random_attendee(urlname , event_id)
    attendees = self.attendence(urlname , event_id)
    attendees.sample.member
end
```

what  do you think @vitortalaia ?

2017-02-14 11:38 UTC, vitortalaia commented on app/services/randsome.rb
> +end
This file indentation is different from the rest (2 spaces) :nail_care:

2017-02-14 15:15 UTC, CaiqueMitsuoka requested changes

2017-02-14 15:15 UTC, CaiqueMitsuoka commented on app/controllers/events_controller.rb
> +    person = attendes.sample.member
I've made a proposal in your other PR. Please look there.

2017-02-14 15:15 UTC, CaiqueMitsuoka commented on app/services/randsome.rb
> +        attendees.sample.member
This should be `attendees.sample[:member]`. The `meetup.attendance`'s return is an array of hashs.

2017-02-14 15:21 UTC, Vitormdias commented
Done @CaiqueMitsuoka @vitortalaia

2017-02-14 16:01 UTC, CaiqueMitsuoka commented on config/routes.rb
> +  get '/events/:urlname/:event_id/random', to: 'events#random'
I think this name can me discussed, neither way, to rename that route is necessary rename the template too.

2017-02-14 16:01 UTC, CaiqueMitsuoka commented on config/routes.rb
> +  get '/events/:urlname/:event_id/random', to: 'events#random'
I think since that method gives an attendee insted of an event, the name random_attendee is more suitable giving its context.

2017-02-14 16:26 UTC, CaiqueMitsuoka approved these changes

2017-02-14 16:26 UTC, merged