Chore/tests for events controller and meetup service
CaiqueMitsuoka/randsome_meetup pull request #16
Opened 2017-02-14 18:03 UTC by CaiqueMitsuoka

2017-02-14 18:04 UTC, CaiqueMitsuoka commented
@kleberngueriero

2017-02-15 12:02 UTC, kleberngueriero commented
About the commits:

You could instead of adding something in one commit and then removing it, just edit the first one to not add it. e.g.: you added the schema.rb in [ Fix tests](https://github.com/CaiqueMitsuoka/randsome_meetup/pull/16/commits/ff03174d0d89d8320a2251ab9a028f53534b8981) and then there is a commit [Remove db/schema.rb](https://github.com/CaiqueMitsuoka/randsome_meetup/pull/16/commits/d81a07653e9dd3cc1c9793c1ec78a0ffefecaeac) just to remove it. When it's about the same branch, you didin't merge it to master yet, and you're the only one working on it, you're still in time to edit the commits to avoid "fixing commits".

2017-02-15 16:41 UTC, Vitormdias approved these changes

2017-02-15 18:26 UTC, kleber-gueriero requested changes

2017-02-15 18:26 UTC, kleber-gueriero commented on spec/controllers/events_controller_spec.rb
> +    @randsome ||= double('Randsome',
When using RSpec's `let`, you only need to return the value inside the block, you don't need to assign it to this "@randsome", and if I remember I can remember, the `let` kinda already does the `||=` thing.

2017-02-15 18:26 UTC, kleber-gueriero commented on spec/controllers/events_controller_spec.rb
> +    it 'assign event' do
Are you creating expectations only for blank results?

2017-02-15 18:26 UTC, kleber-gueriero commented on spec/services/base_meetup_spec.rb
> +  let(:random_hash_key) { @random_hash_key ||= SecureRandom.hex }
Here would be the same as in the comment before about the `let`

2017-02-15 19:58 UTC, CaiqueMitsuoka commented on spec/controllers/events_controller_spec.rb
> +    it 'assign event' do
No, thats actually because #show calls for `randsome.available_events` with return a empty as it is set in the line 7 and stubed in the line 37.

2017-02-16 13:29 UTC, merged