Add cache to meetup-api requests
CaiqueMitsuoka/randsome_meetup pull request #18
Opened 2017-02-16 14:56 UTC by CaiqueMitsuoka

2017-02-16 15:02 UTC, CaiqueMitsuoka commented
@kleberngueriero

2017-02-16 17:04 UTC, Vitormdias reviewed
@CaiqueMitsuoka

2017-02-16 17:05 UTC, Vitormdias requested changes
Grammar issues:

atempts -> attempts

2017-02-17 16:35 UTC, kleber-gueriero requested changes

2017-02-17 16:35 UTC, kleberngueriero commented on config/environments/development.rb
> +  config.cache_store = :memory_store
I think it would be good to deactivate the cache in development too, so when you're testing a new feature you won't have surprises.

2017-02-20 19:25 UTC, Vitormdias approved these changes

2017-02-20 19:25 UTC, merged